Send correlation id to backbone
nmshd/runtime pull request #268
Opened 2024-09-11 13:28 UTC by sebbi08

# Readiness checklist

-   [x] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-09-12 07:24 UTC, Milena-Czierlinski commented
I'm not sure if adding a newline actually counts as updating a test. :D Is there a way we can truly test this feature?

2024-09-12 07:26 UTC, jkoenig134 approved these changes

2024-09-12 07:42 UTC, jkoenig134 commented
> Is there a way we can truly test this feature?

there should be a way. But I think it would require some mocking of the rest client.

2024-09-12 07:47 UTC, sebbi08 commented
I added some test but forgot to add the file :/

2024-09-12 07:48 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +        // Arrange
comments?

2024-09-12 07:48 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +        const interceptor = new RequestInterceptor((testAccount as any).synchronization.client);
what happened to beforeAll?

2024-09-12 07:48 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +        await connection.close();
for cleanup we have afterEach / afterAll

2024-09-12 07:54 UTC, jkoenig134 requested changes

2024-09-12 07:54 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    beforeAll(async function () {
```suggestion
    let interceptor: RequestInterceptor;

    beforeAll(async function () {
```

2024-09-12 07:54 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    test("should send correlation id to the backend when given", async function () {
```suggestion
    });

    test("should send correlation id to the backend when given", async function () {
```

2024-09-12 07:55 UTC, britsta commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    test("should send correlation id to the backend when given", async function () {
Writing "backbone" instead of "backend" as you do in the PR title should be more precise.

2024-09-12 07:55 UTC, britsta commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    beforeAll(async function () {
Please add an empty line before `beforeAll`.

2024-09-12 07:55 UTC, britsta commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    test("should send correlation id to the backend when given", async function () {
Please add an empty line after `afterAll`.

2024-09-12 07:59 UTC, britsta commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    beforeAll(async function () {
Julian was faster :D

2024-09-12 08:23 UTC, jkoenig134 commented on packages/transport/test/core/backbone/CorrelationId.test.ts
> +    beforeAll(async function () {
:)

2024-09-13 06:26 UTC, jkoenig134 commented
@sebbi08 we don't need correlation IDs for every request? My hope would be to have one in the whole runtime scope to also be able to use it in the app.

2024-09-13 06:56 UTC, sebbi08 commented
> @sebbi08 we don't need correlation IDs for every UseCase? My hope would be to have one in the whole runtime scope to also be able to use it in the app.

Ah, i see. The problem I see with this is that we cannot distinguish between the different actions of a user in one session, as all will have the same. Or are you creating a new runtime for each action?

2024-09-13 06:59 UTC, jkoenig134 commented
I don't, but why do we have to create a new runtime when we create correlation id's for each usecase?

2024-09-13 07:06 UTC, jkoenig134 approved these changes

2024-09-13 07:09 UTC, jkoenig134 requested changes
I have to check something within the correlation-id lib

2024-09-13 11:31 UTC, merged