Sharing a request with youself now shows a propper error message
nmshd/runtime pull request #280
Opened 2024-09-20 14:20 UTC by sebbi08

Before, the error was like "There is no relationship to x"

# Readiness checklist

-   [ ] I added/updated tests.
-   [x] I ensured that the PR title is good enough for the changelog.
-   [x] I labeled the PR.

2024-09-20 14:36 UTC, Milena-Czierlinski commented on packages/consumption/src/consumption/ConsumptionCoreErrors.ts
> +    public cannotShareARequestWithYourself() {
I think usually we don't have an "a" in the name of errors e.g. we have cannotShareRelationshipAttributeOfPendingRelationship above and not cannotShare**A**RelationshipAttributeOf**A**PendingRelationship. So, I'd rather name it "cannotShareRequestWithYourself". But that's just a detail, I'm not sure how strict we are with this in general.

2024-09-20 14:38 UTC, Milena-Czierlinski commented
Also, if you want to be thorough you could add a test for this. ;)

2024-09-20 14:56 UTC, jkoenig134 commented on packages/consumption/src/modules/requests/outgoing/OutgoingRequestsController.ts
I am missing newlines here..

2024-09-23 06:35 UTC, jkoenig134 commented
I am missing a test here.

2024-09-23 06:47 UTC, jkoenig134 submitted a review, later dismissed

2024-09-23 07:20 UTC, Milena-Czierlinski requested changes

2024-09-23 07:20 UTC, Milena-Czierlinski commented on packages/consumption/src/consumption/ConsumptionCoreErrors.ts
> +        return new CoreError("error.consumption.requests.cannotShareARequestWithYourself", "You cannot share a Request with yourself.");
You need to also remove the "A" from the error code.

2024-09-23 07:23 UTC, Milena-Czierlinski approved these changes

2024-09-23 07:30 UTC, merged