Fix/Remove 'succeeds' property of successors of predecessor was deleted
nmshd/runtime pull request #70
Opened 2024-03-19 13:11 UTC by Milena-Czierlinski

2024-03-19 13:22 UTC, slavistan approved these changes

2024-03-20 07:06 UTC, jkoenig134 commented on packages/runtime/src/useCases/consumption/attributes/DeletePeerSharedAttributeAndNotifyOwner.ts
> +            successor.succeeds = undefined;
see above

2024-03-20 07:06 UTC, jkoenig134 requested changes
only small comments

2024-03-20 08:41 UTC, Milena-Czierlinski commented on packages/runtime/src/useCases/consumption/attributes/DeleteOwnSharedAttributeAndNotifyPeer.ts
> +            successor.succeeds = undefined;
Is this some built-in function? The compiler doesn't complain, but it doesn't change `successor.succeeds`.

2024-03-20 08:42 UTC, jkoenig134 approved these changes

2024-03-20 08:48 UTC, merged